using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.AspNetCore.Core")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.SqlServer.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.PostgreSQL.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.MySQL.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.StressTests")]
[assembly: InternalsVisibleTo("Sample.ConsoleApp")]

[assembly: InternalsVisibleTo("Cleipnir.Flows.Sample.ConsoleApp")]
[assembly: InternalsVisibleTo("Cleipnir.Flows")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Tests.AspNet")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Wolverine.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Wolverine.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Rebus.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.NServiceBus.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.NServiceBus.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Test.AspNet")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Rebus.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.MassTransit.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.MassTransit.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.MassTransit.RabbitMq.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Sample.Presentation.AspNet")]
[assembly: InternalsVisibleTo("Cleipnir.Flows.Sample.Presentation")]