using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.AspNetCore.Core")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.SqlServer.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.PostgreSQL.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.MariaDB.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.StressTests")]
[assembly: InternalsVisibleTo("Sample.ConsoleApp")]

[assembly: InternalsVisibleTo("Cleipnir.Sample.ConsoleApp")]
[assembly: InternalsVisibleTo("Cleipnir")]
[assembly: InternalsVisibleTo("Cleipnir.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Tests.AspNet")]
[assembly: InternalsVisibleTo("Cleipnir.Wolverine.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.Wolverine.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Rebus.Console")]
[assembly: InternalsVisibleTo("Cleipnir.NServiceBus.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.NServiceBus.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Test.AspNet")]
[assembly: InternalsVisibleTo("Cleipnir.Rebus.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.MassTransit.Console")]
[assembly: InternalsVisibleTo("Cleipnir.MassTransit.Tests")]
[assembly: InternalsVisibleTo("Cleipnir.MassTransit.RabbitMq.Console")]
[assembly: InternalsVisibleTo("Cleipnir.Sample.Presentation.AspNet")]
[assembly: InternalsVisibleTo("Cleipnir.Sample.Presentation")]

[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.MariaDB")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.PostgreSQL")]
[assembly: InternalsVisibleTo("Cleipnir.ResilientFunctions.SqlServer")]