name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Pipeline
    strategy:
      fail-fast: false
      matrix:
        test-project:
          - Core/Cleipnir.ResilientFunctions.Tests
          - Stores/MariaDB/Cleipnir.ResilientFunctions.MariaDB.Tests
          - Stores/PostgreSQL/Cleipnir.ResilientFunctions.PostgreSQL.Tests
          - Stores/SqlServer/Cleipnir.ResilientFunctions.SqlServer.Tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '10.0.x'

      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build

      - run: dotnet build Cleipnir.ResilientFunctions.sln

      - run: dotnet run --project ./Stores/EnsureDatabaseConnections/EnsureDatabaseConnections.csproj --no-build

      - run: dotnet test ./${{ matrix.test-project }} --no-build --logger "console;verbosity=detailed"

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
